server:
  port: 9998
spring:
  datasource:
    username: root
    password: wushuai
    url: jdbc:mysql://localhost:3306/seata?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: stock-seata