server:
  port: 8070
spring:
  application:
    name: auth-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 # 配置sentinel服务端
      web-context-unify: false # 默认将调用链路收敛
      datasource:
        flow-rule:
          nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
            data-id: auth-sentinel-flow-rule
            rule-type: flow