server:
  port: 8088
spring:
  application:
    name: api-gateway
  cloud:
    gateway: #gateway配置
      routes:
        - id: alibaba_order_seata_route #路由唯一表示
          uri: http://127.0.0.1:9999
          #断言规则，用于路由规则的匹配
          predicates:
            - Path=/order-server/**
            #- CheckAuth=wushuai #自定义的路由断言
          filters: #过滤器
            - StripPrefix=1 #转发之前，去掉路由的第一层路径，即断言中配置的path
            #- CheckAuth=wushuai
      # 跨域配置
      globalcors:
        cors-configurations:
          '[**]': #允许跨域访问的资源
            allowed-origins: "*" #跨域允许来源
            allowed-methods:
              - GET
              - POST
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080